DIF,Distrito Federal
AGS,Aguascalientes
BCN,Baja California
BCS,Baja California Sur
CAM,Campeche
CHP,Chiapas
CHI,Chihuahua
COA,Coahuila
COL,Colima
DUR,Durango
GTO,Guanajuato
GRO,Guerrero
HGO,Hidalgo
JAL,Jalisco
MEX,México
MIC,Michoacán
MOR,Morelos
NAY,Nayarit
NLE,Nuevo León
OAX,Oaxaca
PUE,Puebla
QRO,Querétaro
ROO,Quintana Roo
SLP,San Luis Potosí
SIN,Sinaloa
SON,Sonora
TAB,Tabasco
TAM,Tamaulipas
TLX,Tlaxcala
VER,Veracruz
YUC,Yucatán
ZAC,Zacatecas
